/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CustomerController;
import Controller.TextFieldLengthFilter;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Random;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Shahe
 */
public class CustomerRegister extends javax.swing.JFrame {

    int otp = 0;

    /**
     * Creates new form CustomerRegister
     */
    public CustomerRegister() {
        initComponents();

        txt_firstName.setDocument(new TextFieldLengthFilter(15));
        txt_lastName.setDocument(new TextFieldLengthFilter(15));
        txt_streetAddress.setDocument(new TextFieldLengthFilter(50));
        txt_city.setDocument(new TextFieldLengthFilter(20));
        txt_email.setDocument(new TextFieldLengthFilter(125));
        txt_telephone.setDocument(new TextFieldLengthFilter(10));
        txt_otp.setDocument(new TextFieldLengthFilter(4));
        txt_username.setDocument(new TextFieldLengthFilter(30));
        txt_password.setDocument(new TextFieldLengthFilter(12));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_telephone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_confirmPassword = new javax.swing.JPasswordField();
        btn_register = new javax.swing.JButton();
        txt_errorMessage = new javax.swing.JLabel();
        btn_sendOTP = new javax.swing.JButton();
        txt_otp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_streetAddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_email = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/1674385132232_1300x145.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setText("R E G I S T E R");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("First Name      :");

        txt_firstName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Password               :");

        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Username              :");

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Last Name       :");

        txt_lastName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Telephone       :");

        txt_telephone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Email               :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Street Address       :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("City                       :");

        txt_city.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Confirm Password  :");

        txt_confirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_register.setBackground(new java.awt.Color(63, 196, 243));
        btn_register.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        txt_errorMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        btn_sendOTP.setBackground(new java.awt.Color(63, 196, 243));
        btn_sendOTP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sendOTP.setText("Send OTP");
        btn_sendOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendOTPActionPerformed(evt);
            }
        });

        txt_otp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("OTP                 :");

        txt_streetAddress.setColumns(20);
        txt_streetAddress.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_streetAddress.setRows(5);
        jScrollPane1.setViewportView(txt_streetAddress);

        txt_email.setColumns(20);
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_email.setRows(5);
        jScrollPane2.setViewportView(txt_email);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_sendOTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_telephone)
                    .addComponent(txt_lastName)
                    .addComponent(txt_firstName)
                    .addComponent(txt_otp)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txt_password)
                            .addComponent(txt_confirmPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_city)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(39, 39, 39))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(430, 430, 430))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(486, 486, 486))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 63, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_sendOTP)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_otp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btn_register)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        if (txt_firstName.getText().isEmpty()) {
            txt_errorMessage.setText("* First Name cannot be blank");
        } else if (!txt_firstName.getText().matches("^[a-zA-Z]+$")) {
            txt_errorMessage.setText("*Invalid name");
        } else if (!txt_firstName.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("First Name cannot be space");
        } else if (txt_lastName.getText().isEmpty()) {
            txt_errorMessage.setText("* Last Name cannot be blank");
        } else if (!txt_lastName.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("Last Name cannot be space");
        } else if (!txt_lastName.getText().matches("^[a-zA-Z]+$")) {
            txt_errorMessage.setText("* Invalid name");
        } else if (txt_telephone.getText().isEmpty()) {
            txt_errorMessage.setText("* Telephone cannot be blank");
        } else if (!txt_telephone.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("*Telephone Number cannot be space");
        } else if (!txt_telephone.getText().matches("^(?:7|0|(?:\\+94))[0-9]{9,10}$")) {
            txt_errorMessage.setText("Telephone number not in correct format eg: 0712345678");
        } else if (txt_telephone.getText().matches("^[a-zA-Z]+$")) {
            txt_errorMessage.setText("* Invalid Telephone Number");
        } else if (txt_email.getText().isEmpty()) {
            txt_errorMessage.setText("* Email cannot be blank");
        } else if (!txt_email.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.(com)+)*$")) {
            txt_errorMessage.setText("* Email not in correct format eg: someone@example.com ");
        } else if (txt_streetAddress.getText().isEmpty()) {
            txt_errorMessage.setText("* Street Address cannot be blank");
        } else if (!txt_streetAddress.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("Street address cannot be space");
        } else if (!txt_streetAddress.getText().matches("^[a-zA-Z]+$")) {
            txt_errorMessage.setText("* Invalid Stress address");
        } else if (txt_city.getText().isEmpty()) {
            txt_errorMessage.setText("* City cannot be blank");
        } else if (!txt_city.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("city name cannot be space");
        } else if (!txt_city.getText().matches("^[a-zA-Z]+$")) {
            txt_errorMessage.setText("* Invalid City");
        } else if (txt_username.getText().isEmpty()) {
            txt_errorMessage.setText("* Username cannot be blank");
        } else if (!txt_username.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("Username cannot be space");
        } else if (txt_password.getText().isEmpty()) {
            txt_errorMessage.setText("* Password cannot be blank");
        } else if (!txt_password.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("Password cannot be space");
        } else if (txt_confirmPassword.getText().isEmpty()) {
            txt_errorMessage.setText("* Confirm Password cannot be blank");
        } else if (!Arrays.equals(txt_password.getPassword(), txt_confirmPassword.getPassword())) {
            txt_errorMessage.setText("* Password mismatch");
        } else if (!txt_confirmPassword.getText().matches(".*\\S+.*")) {
            txt_errorMessage.setText("Confirm password cannot be space");
        } 
        else {
            txt_errorMessage.setText("");
            if (!txt_otp.getText().matches("^[0-9]+$")) {
                txt_errorMessage.setText("* OTP cannot contain letters");
            } else if (txt_otp.getText().isEmpty()) {
                txt_errorMessage.setText("* OTP cannot be blank");
            } else if (Integer.parseInt(txt_otp.getText()) == otp) {
                txt_errorMessage.setText("");
                CustomerController cus = new CustomerController();

                if (cus.register(txt_firstName.getText(), txt_lastName.getText(), txt_streetAddress.getText(), txt_city.getText(), txt_email.getText(), Integer.parseInt(txt_telephone.getText()), txt_username.getText(), txt_password.getText())) {
                    JOptionPane.showMessageDialog(null, "You are registered !! Welcome to New City Pharmacy", "Success", JOptionPane.INFORMATION_MESSAGE);

                    txt_firstName.setText("");
                    txt_lastName.setText("");
                    txt_streetAddress.setText("");
                    txt_city.setText("");
                    txt_telephone.setText("");
                    txt_username.setText("");
                    txt_password.setText("");
                    txt_confirmPassword.setText("");
                    txt_otp.setText("");
                    txt_email.setText("");

                    UserLogin obj = new UserLogin();
                    obj.setVisible(true);
                    this.hide();

                } else {
                    JOptionPane.showMessageDialog(null, "Register unsuccessful. Please try again", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                txt_errorMessage.setText("* OTP is not correct. Please try again.");
            }

        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        UserLogin obj = new UserLogin();
        obj.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_sendOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendOTPActionPerformed

        if (txt_email.getText().isEmpty()) {
            txt_errorMessage.setText("* Email cannot be blank");
        } else if (!txt_email.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.(com)+)*$")) {
            txt_errorMessage.setText("* Email not in correct format eg: someone@example.com ");
        } else {

            String email = txt_email.getText();  // Replace with the recipient's email address
            // Generate a random 4-digit OTP
            Random random = new Random();
            otp = random.nextInt(9000) + 1000;

            sendEmail(email, otp);
        }
    }//GEN-LAST:event_btn_sendOTPActionPerformed

    public void sendEmail(String email, int otp) {
        // Sender's email and password
        final String username = "daredevildare600@gmail.com";
        final String password = "bgxckfngnothstbo";

        // Configure properties for the mail session
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        // Create a new session
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            // Create a new message
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
            message.setSubject("Your OTP");
            message.setText("Your OTP is " + otp);

            // Send the message
            Transport.send(message);

            JOptionPane.showMessageDialog(null, "OTP sent successfully to " + email, "Error", JOptionPane.INFORMATION_MESSAGE);

        } catch (MessagingException e) {
            JOptionPane.showMessageDialog(null, "Email could not be sent for unknown reasons " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_sendOTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_city;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JTextArea txt_email;
    private javax.swing.JLabel txt_errorMessage;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_otp;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextArea txt_streetAddress;
    private javax.swing.JTextField txt_telephone;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
