/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.PrescriptionController;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.awt.*;
import java.nio.file.Path;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Shahe
 */
public class CustomerUploadPrescription extends javax.swing.JInternalFrame {

    ArrayList<Path> imageFiles = new ArrayList<>();

    /**
     * Creates new form CustomerUploadPrescription
     */
    public CustomerUploadPrescription() {
        initComponents();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        btn_delete_1.setVisible(false);
        btn_delete_2.setVisible(false);
        btn_delete_3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_chooseFiles = new javax.swing.JButton();
        btn_confirm = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        pb_1 = new javax.swing.JLabel();
        pb_3 = new javax.swing.JLabel();
        pb_2 = new javax.swing.JLabel();
        btn_delete_1 = new javax.swing.JButton();
        btn_delete_2 = new javax.swing.JButton();
        btn_delete_3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1120, 670));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Upload Prescription File/s");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        btn_chooseFiles.setBackground(new java.awt.Color(63, 196, 243));
        btn_chooseFiles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_chooseFiles.setText("Choose Files");
        btn_chooseFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooseFilesActionPerformed(evt);
            }
        });

        btn_confirm.setBackground(new java.awt.Color(63, 196, 243));
        btn_confirm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_confirm.setText("Confirm");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(63, 196, 243));
        btn_back.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        pb_1.setBackground(new java.awt.Color(255, 255, 255));
        pb_1.setOpaque(true);

        pb_3.setBackground(new java.awt.Color(255, 255, 255));
        pb_3.setOpaque(true);

        pb_2.setBackground(new java.awt.Color(255, 255, 255));
        pb_2.setOpaque(true);

        btn_delete_1.setBackground(new java.awt.Color(63, 196, 243));
        btn_delete_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_delete_1.setText("Delete");
        btn_delete_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_1ActionPerformed(evt);
            }
        });

        btn_delete_2.setBackground(new java.awt.Color(63, 196, 243));
        btn_delete_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_delete_2.setText("Delete");
        btn_delete_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_2ActionPerformed(evt);
            }
        });

        btn_delete_3.setBackground(new java.awt.Color(63, 196, 243));
        btn_delete_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_delete_3.setText("Delete");
        btn_delete_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_confirm)
                .addGap(18, 18, 18)
                .addComponent(btn_back)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(pb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btn_chooseFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(474, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pb_2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete_2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(btn_chooseFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirm)
                    .addComponent(btn_back))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chooseFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooseFilesActionPerformed

        if (pb_1.getIcon() == null) {
            try {
                String filename;
                JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);
                BufferedImage img = null;
                File file = chooser.getSelectedFile();

                filename = file.getAbsolutePath();

                img = ImageIO.read(new File(filename));
                Image image = img.getScaledInstance(pb_1.getWidth(), pb_1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageicon = new ImageIcon(image);

                if (imageFiles.contains(file.toPath())) {
                    JOptionPane.showMessageDialog(null, "This image is already selected and cannot be added again.", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {
                    pb_1.setIcon(imageicon);
                    imageFiles.add(0, file.toPath());
                    btn_delete_1.setVisible(true);
                }
            } catch (IOException | NullPointerException e) {
                JOptionPane.showMessageDialog(null, "The selected file is not an image " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else if (pb_2.getIcon() == null) {

            try {
                String filename;
                JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);
                BufferedImage img = null;
                File file = chooser.getSelectedFile();

                filename = file.getAbsolutePath();

                img = ImageIO.read(new File(filename));
                Image image = img.getScaledInstance(pb_2.getWidth(), pb_2.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageicon = new ImageIcon(image);

                if (imageFiles.contains(file.toPath())) {
                    JOptionPane.showMessageDialog(null, "This image is already selected and cannot be added again.", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {
                    pb_2.setIcon(imageicon);
                    imageFiles.add(1, file.toPath());
                    btn_delete_2.setVisible(true);
                }

            } catch (IOException | NullPointerException e) {
                JOptionPane.showMessageDialog(null, "The selected file is not an image " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else if (pb_3.getIcon() == null) {
            JOptionPane.showMessageDialog(null, "This image is already selected and cannot be added again.", "Warning", JOptionPane.WARNING_MESSAGE);
            try {
                String filename;
                JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);
                BufferedImage img = null;
                File file = chooser.getSelectedFile();

                filename = file.getAbsolutePath();

                img = ImageIO.read(new File(filename));
                Image image = img.getScaledInstance(pb_3.getWidth(), pb_3.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageicon = new ImageIcon(image);

                if (imageFiles.contains(file.toPath())) {

                } else {
                    pb_3.setIcon(imageicon);
                    imageFiles.add(2, file.toPath());
                    btn_delete_3.setVisible(true);
                }

            } catch (IOException | NullPointerException e) {
                JOptionPane.showMessageDialog(null, "The selected file is not an image " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "You have reached the maximum number of images to upload", "Error", JOptionPane.WARNING_MESSAGE);
        }
        System.out.println(imageFiles);


    }//GEN-LAST:event_btn_chooseFilesActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed

        if (pb_1.getIcon() == null && pb_2.getIcon() == null && pb_3.getIcon() == null) {
            JOptionPane.showMessageDialog(null, "You need to upload at least one image to proceed.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            PrescriptionController obj = new PrescriptionController();

            if (obj.uploadPrescription(CustomerDashboard.customerId, imageFiles)) {
                JOptionPane.showMessageDialog(null, "Your prescription has been uploaded.", "Success", JOptionPane.INFORMATION_MESSAGE);
                CustomerMyPrecription obj1 = new CustomerMyPrecription();
                CustomerDashboard.SendLoader(obj1);
            } else {
                JOptionPane.showMessageDialog(null, "Your prescription has not been uploaded. Please try again", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        CustomerMyPrecription obj = new CustomerMyPrecription();
        CustomerDashboard.SendLoader(obj);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_delete_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_2ActionPerformed
        if (pb_2.getIcon() == null) {

        } else {
            pb_2.setIcon(null);
            imageFiles.set(1, null);
            btn_delete_2.setVisible(false);
            System.out.println(imageFiles);
        }
    }//GEN-LAST:event_btn_delete_2ActionPerformed

    private void btn_delete_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_1ActionPerformed
        if (pb_1.getIcon() == null) {

        } else {
            pb_1.setIcon(null);
            imageFiles.set(0, null);
            btn_delete_1.setVisible(false);
            System.out.println(imageFiles);
        }
    }//GEN-LAST:event_btn_delete_1ActionPerformed

    private void btn_delete_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_3ActionPerformed

        if (pb_3.getIcon() == null) {

        } else {
            pb_3.setIcon(null);
            imageFiles.set(2, null);
            btn_delete_3.setVisible(false);
            System.out.println(imageFiles);
        }
    }//GEN-LAST:event_btn_delete_3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_chooseFiles;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_delete_1;
    private javax.swing.JButton btn_delete_2;
    private javax.swing.JButton btn_delete_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pb_1;
    private javax.swing.JLabel pb_2;
    private javax.swing.JLabel pb_3;
    // End of variables declaration//GEN-END:variables
}
