package View;

import Controller.PrescriptionController;
import Controller.PrescriptionEntriesUI;
import Model.Prescription;
import java.awt.Dimension;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Shahe
 */
public class PharmacistPrescriptions extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prescriptions1
     */
    public PharmacistPrescriptions() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
         int x =0;
        int y =10;
        PrescriptionController obj = new PrescriptionController();
        List<Prescription> prescriptionList = obj.getPrescriptionDetail();
        
        for(Prescription prescription : prescriptionList){
            
            PrescriptionEntriesUI tile = new PrescriptionEntriesUI();
            tile.createPrescriptionUI(jPanel2, x, y, prescription.getPrescriptionId(), prescription.getDate(), prescription.getStatus());
            
            y = y + 80;
            
            if(y > jPanel2.getHeight())
            {
                jPanel2.setPreferredSize(new Dimension(1075,y+100));
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_all = new javax.swing.JButton();
        btn_pending = new javax.swing.JButton();
        btn_rejected = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Issued Date");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Status");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Action");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Prescription ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Prescriptions");

        btn_back.setBackground(new java.awt.Color(63, 196, 243));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_all.setBackground(new java.awt.Color(63, 196, 243));
        btn_all.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_all.setText("All");
        btn_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allActionPerformed(evt);
            }
        });

        btn_pending.setBackground(new java.awt.Color(63, 196, 243));
        btn_pending.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_pending.setText("Pending");
        btn_pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pendingActionPerformed(evt);
            }
        });

        btn_rejected.setBackground(new java.awt.Color(63, 196, 243));
        btn_rejected.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_rejected.setText("Rejected");
        btn_rejected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rejectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196)
                        .addComponent(jLabel3)
                        .addGap(195, 195, 195)
                        .addComponent(jLabel4)
                        .addGap(189, 189, 189)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_all, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pending, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_rejected, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_all, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pending, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_rejected, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        PharmacistHomePage obj = new PharmacistHomePage();
        PharmacistDashboard.sendLoader(obj);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allActionPerformed
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        int x =0;
        int y =10;
        PrescriptionController obj = new PrescriptionController();
        List<Prescription> prescriptionList = obj.getPrescriptionDetail();
        
        for(Prescription prescription : prescriptionList){
            
            PrescriptionEntriesUI tile = new PrescriptionEntriesUI();
            tile.createPrescriptionUI(jPanel2, x, y, prescription.getPrescriptionId(), prescription.getDate(), prescription.getStatus());
            
            y = y + 80;
            
            if(y > jPanel2.getHeight())
            {
                jPanel2.setPreferredSize(new Dimension(1075,y+100));
            }
            
        }
    }//GEN-LAST:event_btn_allActionPerformed

    private void btn_pendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pendingActionPerformed
         jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        int x =0;
        int y =10;
        PrescriptionController obj = new PrescriptionController();
        List<Prescription> prescriptionList = obj.getPendingPrescriptionDetails();
        
        for(Prescription prescription : prescriptionList){
            
            PrescriptionEntriesUI tile = new PrescriptionEntriesUI();
            tile.createPrescriptionUI(jPanel2, x, y, prescription.getPrescriptionId(), prescription.getDate(), prescription.getStatus());
            
            y = y + 80;
            
            if(y > jPanel2.getHeight())
            {
                jPanel2.setPreferredSize(new Dimension(1075,y+100));
            }
            
        }
    }//GEN-LAST:event_btn_pendingActionPerformed

    private void btn_rejectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rejectedActionPerformed
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        int x =0;
        int y =10;
        PrescriptionController obj = new PrescriptionController();
        List<Prescription> prescriptionList = obj.getRejectedPrescriptionDetails();
        
        for(Prescription prescription : prescriptionList){
            
            PrescriptionEntriesUI tile = new PrescriptionEntriesUI();
            tile.createPrescriptionUI(jPanel2, x, y, prescription.getPrescriptionId(), prescription.getDate(), prescription.getStatus());
            
            y = y + 80;
            
            if(y > jPanel2.getHeight())
            {
                jPanel2.setPreferredSize(new Dimension(1075,y+100));
            }
            
        }
    }//GEN-LAST:event_btn_rejectedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_all;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_pending;
    private javax.swing.JButton btn_rejected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
